name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6', '1.9']  # Test multiple Julia versions
        os: [ubuntu-latest, windows-latest, macos-latest]  # Test on multiple OSes

    steps:
      - uses: actions/checkout@v3

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - uses: julia-actions/cache@v1

      # Add documentation generation check (optional)
      - name: Build documentation
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")'
        if: matrix.julia-version == '1.9' && matrix.os == 'ubuntu-latest'

      - name: Run tests
        env:
          JULIA_NUM_THREADS: 2  # Optional: set number of threads
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test(coverage=true)'

      # Optional: Upload coverage to Codecov
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
